services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mohaymen
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - .:/app
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Database=mohaymen;Username=postgres;Password=1234;
    command: >
      bash -c "dotnet tool install --global dotnet-ef &&
               export PATH=\"$PATH:/root/.dotnet/tools\" &&
               dotnet ef database update --project AnalysisData/AnalysisData/AnalysisData.csproj"

  web:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Database=mohaymen;Username=postgres;Password=1234;
    ports:
      - "8080:80"

volumes:
  pgdata:
